-- Gerado automaticamente por scripts/generate-seed.ts — NÃO editar à mão
BEGIN;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT', 'shoulder', 'Lesão do manguito rotador', NULL, 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', 'PROT_RCR_STANDARD', ARRAY['ASES','SANE','CONSTANT']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_INST_ANT', 'shoulder', 'Instabilidade glenoumeral anterior', NULL, 1, 'SH_INST_ANT.diagnosis.v1', 'SH_INST_ANT.intraop.v1', 'SH_INST_ANT.v1', 'PROT_BANKART', ARRAY['SANE','ROWE']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_INST_POST', 'shoulder', 'Instabilidade glenoumeral posterior', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_INST_MDI', 'shoulder', 'Instabilidade multidirecional do ombro', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_BICEPS', 'shoulder', 'Lesão do cabo longo do bíceps', NULL, 1, NULL, 'SH_BICEPS.intraop.v1', 'SH_BICEPS.v1', 'PROT_BICEPS_TENODESIS', ARRAY['ASES','SANE']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_AC_DISL', 'shoulder', 'Luxação acromioclavicular', NULL, 1, NULL, 'SH_AC_DISL.intraop.v1', 'SH_AC_DISL.v1', 'PROT_AC_RECON', ARRAY['ASES','SANE']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_AC_OA', 'shoulder', 'Artrose acromioclavicular', NULL, 1, NULL, 'SH_AC_DISL.intraop.v1', 'SH_AC_DISL.v1', 'PROT_DCE', '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_STIFF', 'shoulder', 'Capsulite adesiva / rigidez do ombro', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_CALC', 'shoulder', 'Tendinite calcária do manguito rotador', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_OA_GH', 'shoulder', 'Artrose glenoumeral', NULL, 1, NULL, 'SH_ARTHROPLASTY.intraop.v1', 'SH_ARTHROPLASTY.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_CTA', 'shoulder', 'Artropatia do manguito rotador', NULL, 1, NULL, 'SH_ARTHROPLASTY.intraop.v1', 'SH_ARTHROPLASTY.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_ARTHROPLASTY', 'shoulder', 'Artroplastia do ombro', NULL, 1, NULL, 'SH_ARTHROPLASTY.intraop.v1', 'SH_ARTHROPLASTY.v1', 'PROT_RSA', ARRAY['ASES','SANE','CONSTANT']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_FX_PROX_HUM', 'shoulder', 'Fratura do úmero proximal', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_FX_CLAV', 'shoulder', 'Fratura da clavícula', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_FX_SCAP', 'shoulder', 'Fratura da escápula / glenoide', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_PEC_MAJOR', 'shoulder', 'Rotura do peitoral maior', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_SS_NEURO', 'shoulder', 'Neuropatia do nervo supraescapular', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_SCAP_DYSK', 'shoulder', 'Discinesia escapular', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_SC_JOINT', 'shoulder', 'Lesão da articulação esternoclavicular', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_LAT_EPI', 'elbow', 'Epicondilite lateral', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_MED_EPI', 'elbow', 'Epicondilite medial', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_UCL', 'elbow', 'Lesão do ligamento colateral ulnar (medial)', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_PLRI', 'elbow', 'Instabilidade rotatória posterolateral', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_DISL', 'elbow', 'Luxação do cotovelo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_DBR', 'elbow', 'Rotura do tendão distal do bíceps', NULL, 1, NULL, 'EL_DBR.intraop.v1', 'EL_DBR.v1', 'PROT_DISTAL_BICEPS', ARRAY['SANE','MEPS']::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_TRICEPS', 'elbow', 'Rotura do tendão do tríceps', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_CUBITAL', 'elbow', 'Neuropatia ulnar no cotovelo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_STIFF', 'elbow', 'Rigidez do cotovelo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_OA', 'elbow', 'Artrose do cotovelo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_OCD', 'elbow', 'Osteocondrite dissecante do capítulo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_FX_RH', 'elbow', 'Fratura da cabeça/colo do rádio', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_FX_OLEC', 'elbow', 'Fratura do olécrano', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_FX_DH', 'elbow', 'Fratura do úmero distal', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_FX_COR', 'elbow', 'Fratura do processo coronoide', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_TERRIBLE_TRIAD', 'elbow', 'Tríade terrível do cotovelo', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_MONTEGGIA', 'elbow', 'Fratura-luxação de Monteggia', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('EL_BURSITIS', 'elbow', 'Bursite olecraniana', NULL, 1, NULL, NULL, NULL, NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_TENDINOPATHY', 'shoulder', 'Tendinopatia do manguito rotador', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_PARTIAL', 'shoulder', 'Rotura parcial do manguito rotador', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_FULL', 'shoulder', 'Rotura completa do manguito rotador', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_MASSIVE', 'shoulder', 'Rotura maciça do manguito rotador', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', 'PROT_RCR_MASSIVE', '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_SUBSCAP', 'shoulder', 'Lesão do subescapular', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_RCT_REVISION', 'shoulder', 'Re-rotura do manguito rotador (revisão)', 'SH_RCT', 1, NULL, 'SH_RCT.intraop.v1', 'SH_RCT.v1', NULL, '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
INSERT INTO public.pathology_catalog (code, region, name_pt, parent_code, schema_version, diagnosis_schema_id, intraop_schema_id, report_template, default_protocol_code, proms_default)
VALUES ('SH_SLAP', 'shoulder', 'Lesão SLAP', 'SH_BICEPS', 1, NULL, 'SH_BICEPS.intraop.v1', 'SH_BICEPS.v1', 'PROT_SLAP_REPAIR', '{}'::text[])
ON CONFLICT (code) DO UPDATE SET name_pt = EXCLUDED.name_pt, parent_code = EXCLUDED.parent_code, diagnosis_schema_id = EXCLUDED.diagnosis_schema_id, intraop_schema_id = EXCLUDED.intraop_schema_id, report_template = EXCLUDED.report_template, default_protocol_code = EXCLUDED.default_protocol_code, proms_default = EXCLUDED.proms_default;
COMMIT;
