import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import doctorsRouter from "./doctors";
import patientsRouter from "./patients";
import surgeriesRouter from "./surgeries";
import shoulderSurgeriesRouter from "./shoulder-surgeries";
import followupRouter from "./followup";
import reportsRouter from "./reports";
import patientRouter from "./patient";
import mediaRouter from "./media";
import adminRouter from "./admin";
import storageRouter from "./storage";
import agentRouter from "./agent";
import notificationsRouter from "./notifications";
import { waBroadcastRouter } from "./wa-broadcast";
import { patientAttachmentsRouter } from "./patient-attachments";
import lgpdRouter from "./lgpd";
import secretariesRouter from "./secretaries";
import scheduledSurgeriesRouter from "./scheduled-surgeries";
import statsRouter from "./stats";
import stripeRouter from "./stripe";
import pdfRouter from "./pdf";
import physioRouter from "./physio";
import physioClinicalRouter from "./physio-clinical";
import physioDocumentsRouter from "./physio-documents";
import physioAgendaRouter from "./physio-agenda";
import physioBillingRouter from "./physio-billing";
import rehabInvitesRouter from "./rehab-invites";
import servicesRouter from "./services";
import regenRouter from "./regen";
import analyticsRouter from "./analytics";
import adminAnalyticsRouter from "./admin-analytics";
import adminContentRouter from "./admin-content";
import totpRouter from "./totp";
import preConsultRouter from "./pre-consult";
import patientOrientationsRouter from "./patient-orientations";
import adminWhatsappRouter from "./admin-whatsapp";
import decisionSupportRouter from "./decision-support";
import { subscriptionWriteGuard } from "../middlewares/subscriptionWriteGuard";
import { decisionSupportWriteGuard } from "../lib/decision-support-protection";

const router: IRouter = Router();

router.use(subscriptionWriteGuard);
router.use(healthRouter);
router.use(authRouter);
router.use(doctorsRouter);
router.use(patientsRouter);
router.use(surgeriesRouter);
router.use(shoulderSurgeriesRouter);
router.use(followupRouter);
router.use(reportsRouter);
router.use(patientRouter);
router.use(mediaRouter);
router.use(adminRouter);
router.use(storageRouter);
router.use(agentRouter);
router.use(notificationsRouter);
router.use(waBroadcastRouter);
router.use(patientAttachmentsRouter);
router.use(lgpdRouter);
router.use(secretariesRouter);
router.use(scheduledSurgeriesRouter);
router.use(statsRouter);
router.use(stripeRouter);
router.use(pdfRouter);
router.use(physioRouter);
router.use(physioBillingRouter);
router.use(physioClinicalRouter);
router.use(physioDocumentsRouter);
router.use(physioAgendaRouter);
router.use(rehabInvitesRouter);
router.use(servicesRouter);
router.use(regenRouter);
router.use(analyticsRouter);
router.use(adminAnalyticsRouter);
router.use(adminContentRouter);
router.use(totpRouter);
router.use(preConsultRouter);
router.use(patientOrientationsRouter);
router.use(adminWhatsappRouter);
// Sem os gatilhos só de inserção no banco (lib/db/pre-push/0002), gravação do apoio à decisão → 503.
router.use("/apoio-decisao", decisionSupportWriteGuard);
router.use(decisionSupportRouter);

export default router;
